/*global define*/

define(function () {
    'use strict';

    var CountriesList = [
        { name: "Antigua and Barbuda", code: "antigua-and-barbuda" },
        { name: "Argentina", code: "argentina" },
        { name: "Aruba", code: "aruba" },
        { name: "Bahamas", code: "bahamas" },
        { name: "Barbados", code: "barbados" },
        { name: "Belize", code: "belize" },
        { name: "Bermuda", code: "bermuda" },
        { name: "Bolivia", code: "bolivia" },
        { name: "Brazil", code: "brazil" },
        { name: "Canada", code: "canada" },
        { name: "Cayman Islands", code: "cayman-islands" },
        { name: "Chile", code: "chile" },
        { name: "Colombia", code: "colombia" },
        { name: "Costa Rica", code: "costa-rica" },
        { name: "Cuba", code: "cuba" },
        { name: "Dominica", code: "dominica" },
        { name: "Dominican Republic", code: "dominican-republic" },
        { name: "Ecuador", code: "ecuador" },
        { name: "El Salvador", code: "el-salvador" },
        { name: "Grenada", code: "grenada" },
        { name: "Guatemala", code: "guatemala" },
        { name: "Guyana", code: "guyana" },
        { name: "Haiti", code: "haiti" },
        { name: "Honduras", code: "honduras" },
        { name: "Jamaica", code: "jamaica" },
        { name: "Mexico", code: "mexico" },
        { name: "Nicaragua", code: "nicaragua" },
        { name: "Panama", code: "panama" },
        { name: "Paraguay", code: "paraguay" },
        { name: "Peru", code: "peru" },
        { name: "Puerto Rico", code: "puerto-rico" },
        { name: "Suriname", code: "suriname" },
        { name: "Trinidad and Tobago", code: "trinidad-and-tobago" },
        { name: "United States", code: "united-states" },
        { name: "Uruguay", code: "uruguay" },
        { name: "Venezuela", code: "venezuela" },
        { name: "Albania", code: "albania" },
        { name: "Andorra", code: "andorra" },
        { name: "Austria", code: "austria" },
        { name: "Belarus", code: "belarus" },
        { name: "Belgium", code: "belgium" },
        { name: "Bosnia and Herzegovina", code: "bosnia-and-herzegovina" },
        { name: "Bulgaria", code: "bulgaria" },
        { name: "Croatia", code: "croatia" },
        { name: "Cyprus", code: "cyprus" },
        { name: "Czech Republic", code: "czech-republic" },
        { name: "Denmark", code: "denmark" },
        { name: "Estonia", code: "estonia" },
        { name: "Euro Area", code: "euro-area" },
        { name: "European Union", code: "european-union" },
        { name: "Finland", code: "finland" },
        { name: "France", code: "france" },
        { name: "Germany", code: "germany" },
        { name: "Greece", code: "greece" },
        { name: "Hungary", code: "hungary" },
        { name: "Iceland", code: "iceland" },
        { name: "Ireland", code: "ireland" },
        { name: "Isle of Man", code: "isle-of-man" },
        { name: "Italy", code: "italy" },
        { name: "Kosovo", code: "kosovo" },
        { name: "Latvia", code: "latvia" },
        { name: "Liechtenstein", code: "liechtenstein" },
        { name: "Lithuania", code: "lithuania" },
        { name: "Luxembourg", code: "luxembourg" },
        { name: "Macedonia", code: "macedonia" },
        { name: "Malta", code: "malta" },
        { name: "Moldova", code: "moldova" },
        { name: "Monaco", code: "monaco" },
        { name: "Montenegro", code: "montenegro" },
        { name: "Netherlands", code: "netherlands" },
        { name: "Norway", code: "norway" },
        { name: "Poland", code: "poland" },
        { name: "Portugal", code: "portugal" },
        { name: "Romania", code: "romania" },
        { name: "Russia", code: "russia" },
        { name: "Serbia", code: "serbia" },
        { name: "Slovakia", code: "slovakia" },
        { name: "Slovenia", code: "slovenia" },
        { name: "Spain", code: "spain" },
        { name: "Sweden", code: "sweden" },
        { name: "Switzerland", code: "switzerland" },
        { name: "Turkey", code: "turkey" },
        { name: "Ukraine", code: "ukraine" },
        { name: "United Kingdom", code: "united-kingdom" },
        { name: "Algeria", code: "algeria" },
        { name: "Angola", code: "angola" },
        { name: "Benin", code: "benin" },
        { name: "Botswana", code: "botswana" },
        { name: "Burkina Faso", code: "burkina-faso" },
        { name: "Burundi", code: "burundi" },
        { name: "Cameroon", code: "cameroon" },
        { name: "Cape Verde", code: "cape-verde" },
        { name: "Central African Republic", code: "central-african-republic" },
        { name: "Chad", code: "chad" },
        { name: "Comoros", code: "comoros" },
        { name: "Congo", code: "congo" },
        { name: "Djibouti", code: "djibouti" },
        { name: "Egypt", code: "egypt" },
        { name: "Equatorial-guinea", code: "equatorial-guinea" },
        { name: "Eritrea", code: "eritrea" },
        { name: "Ethiopia", code: "ethiopia" },
        { name: "Gabon", code: "gabon" },
        { name: "Gambia", code: "gambia" },
        { name: "Ghana", code: "ghana" },
        { name: "Guinea", code: "guinea" },
        { name: "Guinea-Bissau", code: "guinea-bissau" },
        { name: "Ivory Coast", code: "ivory-coast" },
        { name: "Kenya", code: "kenya" },
        { name: "Lesotho", code: "lesotho" },
        { name: "Liberia", code: "liberia" },
        { name: "Libya", code: "libya" },
        { name: "Madagascar", code: "madagascar" },
        { name: "Malawi", code: "malawi" },
        { name: "Mali", code: "mali" },
        { name: "Mauritania", code: "mauritania" },
        { name: "Mauritius", code: "mauritius" },
        { name: "Morocco", code: "morocco" },
        { name: "Mozambique", code: "mozambique" },
        { name: "Namibia", code: "namibia" },
        { name: "Niger", code: "niger" },
        { name: "Nigeria", code: "nigeria" },
        { name: "Republic of the Congo", code: "republic-of-the-congo" },
        { name: "Rwanda", code: "rwanda" },
        { name: "São Tomé and Príncipe", code: "sao-tome-and-principe" },
        { name: "Senegal", code: "senegal" },
        { name: "Seychelles", code: "seychelles" },
        { name: "Sierra-leone", code: "sierra-leone" },
        { name: "Somalia", code: "somalia" },
        { name: "South Africa", code: "south-africa" },
        { name: "South Sudan", code: "south-sudan" },
        { name: "Sudan", code: "sudan" },
        { name: "Swaziland", code: "swaziland" },
        { name: "Tanzania", code: "tanzania" },
        { name: "Togo", code: "togo" },
        { name: "Tunisia", code: "tunisia" },
        { name: "Uganda", code: "uganda" },
        { name: "Zambia", code: "zambia" },
        { name: "Zimbabwe", code: "zimbabwe" },
        { name: "Afghanistan", code: "afghanistan" },
        { name: "Armenia", code: "armenia" },
        { name: "Azerbaijan", code: "azerbaijan" },
        { name: "Bahrain", code: "bahrain" },
        { name: "Bangladesh", code: "bangladesh" },
        { name: "Bhutan", code: "bhutan" },
        { name: "Brunei", code: "brunei" },
        { name: "Cambodia", code: "cambodia" },
        { name: "China", code: "china" },
        { name: "East Timor", code: "east-timor" },
        { name: "Georgia", code: "georgia" },
        { name: "Hong-Kong", code: "hong-kong" },
        { name: "India", code: "india" },
        { name: "Indonesia", code: "indonesia" },
        { name: "Iran", code: "iran" },
        { name: "Iraq", code: "iraq" },
        { name: "Israel", code: "israel" },
        { name: "Japan", code: "japan" },
        { name: "Jordan", code: "jordan" },
        { name: "Kazakhstan", code: "kazakhstan" },
        { name: "Kuwait", code: "kuwait" },
        { name: "Kyrgyzstan", code: "kyrgyzstan" },
        { name: "Laos", code: "laos" },
        { name: "Lebanon", code: "lebanon" },
        { name: "Macao", code: "macao" },
        { name: "Malaysia", code: "malaysia" },
        { name: "Maldives", code: "maldives" },
        { name: "Mongolia", code: "mongolia" },
        { name: "Myanmar", code: "myanmar" },
        { name: "Nepal", code: "nepal" },
        { name: "North Korea", code: "north-korea" },
        { name: "Oman", code: "oman" },
        { name: "Palestine", code: "palestine" },
        { name: "Pakistan", code: "pakistan" },
        { name: "Philippines", code: "philippines" },
        { name: "Qatar", code: "qatar" },
        { name: "Saudi Arabia", code: "saudi-arabia" },
        { name: "Singapore", code: "singapore" },
        { name: "South Korea", code: "south-korea" },
        { name: "Sri Lanka", code: "sri-lanka" },
        { name: "Syria", code: "syria" },
        { name: "Taiwan", code: "taiwan" },
        { name: "Tajikistan", code: "tajikistan" },
        { name: "Thailand", code: "thailand" },
        { name: "Turkmenistan", code: "turkmenistan" },
        { name: "United Arab Emirates", code: "united-arab-emirates" },
        { name: "Uzbekistan", code: "uzbekistan" },
        { name: "Vietnam", code: "vietnam" },
        { name: "Yemen", code: "yemen" },
        { name: "Australia", code: "australia" },
        { name: "Fiji", code: "fiji" },
        { name: "Kiribati", code: "kiribati" },
        { name: "New Caledonia", code: "new-caledonia" },
        { name: "New Zealand", code: "new-zealand" },
        { name: "Papua New Guinea", code: "papua-new-guinea" },
        { name: "Samoa", code: "samoa" },
        { name: "Solomon Islands", code: "solomon-islands" },
        { name: "Tonga", code: "tonga" },
        { name: "Vanuatu", code: "vanuatu" }
    ];

    return CountriesList;
});
